export const brand = {
  primary: "#263E8B",
  secondary: "#E3A437",
  accent: "#2CA36B",
};

export const vendors = [
  {
    id: 1,
    company: "Amazing Wedding Planners",
    category: "Wedding",
    owner: "Nadeesha Perera",
    email: "amazingwedding@gmail.com",
    phone: "+94 71 222 3344",
    location: "Colombo",
    rating: 4.9,
    totalOrders: 148,
    totalIncome: "LKR 2,850,000",
    paidAmount: "LKR 2,500,000",
    pendingAmount: "LKR 350,000",
    status: "Active",
    short:
      "Elegant wedding planning with décor, venue styling, guest coordination, and premium photography support.",
    experience: 8,
    projects: 120,
    employees: 24,
    success: 98,
    image:
      "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: 2,
    company: "Royal Event Makers",
    category: "Birthday",
    owner: "Kasun Fernando",
    email: "royalevents@gmail.com",
    phone: "+94 77 445 6789",
    location: "Kandy",
    rating: 4.7,
    totalOrders: 96,
    totalIncome: "LKR 1,650,000",
    paidAmount: "LKR 1,420,000",
    pendingAmount: "LKR 230,000",
    status: "Active",
    short:
      "Creative birthday event team for kids, adults, themed parties, stage setup, and entertainment management.",
    experience: 6,
    projects: 90,
    employees: 16,
    success: 95,
    image:
      "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: 3,
    company: "Glow Party Hub",
    category: "Party",
    owner: "Ayesha Silva",
    email: "glowparty@gmail.com",
    phone: "+94 75 123 9900",
    location: "Galle",
    rating: 4.8,
    totalOrders: 121,
    totalIncome: "LKR 2,100,000",
    paidAmount: "LKR 1,900,000",
    pendingAmount: "LKR 200,000",
    status: "Pending Review",
    short:
      "High-energy event production for private parties, DJ nights, light shows, and full venue coordination.",
    experience: 7,
    projects: 110,
    employees: 20,
    success: 97,
    image:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80",
  },
];

export const clients = [
  {
    id: 1,
    name: "Dilshan Raj",
    email: "dilshanraj@gmail.com",
    phone: "+94 70 555 1122",
    location: "Colombo",
    vendorNeeded: "Amazing Wedding Planners",
    serviceType: "Wedding Full Package",
    paymentStatus: "Partially Paid",
    paid: "LKR 120,000",
    pending: "LKR 30,000",
  },
  {
    id: 2,
    name: "Malsha Fernando",
    email: "malshafernando@gmail.com",
    phone: "+94 76 111 8888",
    location: "Jaffna",
    vendorNeeded: "Royal Event Makers",
    serviceType: "Birthday Gold Package",
    paymentStatus: "Paid",
    paid: "LKR 95,000",
    pending: "LKR 0",
  },
  {
    id: 3,
    name: "Ruvin Peris",
    email: "ruvinperis@gmail.com",
    phone: "+94 78 444 6677",
    location: "Negombo",
    vendorNeeded: "Glow Party Hub",
    serviceType: "Party Light & DJ Setup",
    paymentStatus: "Pending",
    paid: "LKR 40,000",
    pending: "LKR 60,000",
  },
];

export const newVendors = [
  {
    id: 101,
    businessName: "Dream Lens Studio",
    businessType: "Photography",
    businessAddress: "45, Temple Road, Colombo",
    businessContact: "+94 77 123 4567",
    ownerName: "Sajith Perera",
    ownerAddress: "12, Lake View, Colombo",
    ownerContact: "+94 71 456 7890",
    ownerEmail: "dreamlens@gmail.com",
    ownerNIC: "NIC_uploaded.pdf",
    ownerBR: "BR-2025-7788",
    notes: "Wedding and event photography with drone coverage.",
    submittedDate: "2026-03-18",
    status: "Pending Verification",
  },
  {
    id: 102,
    businessName: "Flora Decors",
    businessType: "Decoration",
    businessAddress: "22, Flower Street, Kandy",
    businessContact: "+94 76 222 1133",
    ownerName: "Nimali Fernando",
    ownerAddress: "8, Hill Lane, Kandy",
    ownerContact: "+94 75 888 3322",
    ownerEmail: "floradecors@gmail.com",
    ownerNIC: "NIC_uploaded.pdf",
    ownerBR: "N/A",
    notes: "Wedding flower décor, stage design, and table arrangements.",
    submittedDate: "2026-03-17",
    status: "Pending Verification",
  },
];

export const newClients = [
  {
    id: 201,
    name: "Suren Rajapaksha",
    address: "14, Beach Road, Galle",
    phone: "+94 77 999 1000",
    email: "surenraj@gmail.com",
    eventType: "Wedding",
    nicFile: "client_nic.pdf",
    notes: "Looking for a full wedding package in Galle.",
    submittedDate: "2026-03-18",
  },
  {
    id: 202,
    name: "Piumi Silva",
    address: "88, Main Street, Jaffna",
    phone: "+94 71 456 2000",
    email: "piumis@gmail.com",
    eventType: "Birthday",
    nicFile: "client_nic.pdf",
    notes: "Need decoration and photography for birthday event.",
    submittedDate: "2026-03-16",
  },
];

export const vendorPackages = [
  { name: "Silver", price: "LKR 75,000", items: ["Basic décor", "Event coordination", "Photo coverage"] },
  { name: "Gold", price: "LKR 150,000", items: ["Premium décor", "Photo & video", "Guest support"] },
  { name: "Platinum", price: "LKR 280,000", items: ["Luxury full setup", "Cinematic coverage", "Dedicated event manager"] },
];